MSG
-HDR(Return-Path; <beazley@riverdale.strangeware.ca>)
-HDR(From; "beazley" <beazley@riverdale.strangeware.ca>)
-HDR(To; "weatherbee" <weatherbee@riverdale.strangeware.ca>)
-HDR(Subject; message nested)
-HDR(X-Header0; Header0)
-HDR(X-Header1; Header1)
-HDR(X-Header2; Header2)
-MSG
--HDR(Subject; Part0)
--HDR(X-Header0; Header00)
--HDR(X-Header1; Header01)
--TEXT(text0.txt)
